local_repository(
    name = "build_stack_rules_proto",
    path = "../../../../../cadence_rules_proto",
)

register_toolchains("@build_stack_rules_proto//toolchain:prebuilt")

# == Externals ==

load("@build_stack_rules_proto//deps:core_deps.bzl", "core_deps")

core_deps()

# NOTE: these come before go_rules_dependencies and gazelle_dependencies in
# order to use newer grpc deps.

load("@build_stack_rules_proto//deps:go_core_deps.bzl", "go_core_deps")

go_core_deps()

# == Go ==

load("@io_bazel_rules_go//go:deps.bzl", "go_register_toolchains", "go_rules_dependencies")

go_rules_dependencies()

go_register_toolchains(version = "1.16.2")

# == Gazelle ==

load("@bazel_gazelle//:deps.bzl", "gazelle_dependencies")

gazelle_dependencies()

load("@build_stack_rules_proto//:go_deps.bzl", "gazelle_protobuf_extension_go_deps")

gazelle_protobuf_extension_go_deps()

# == Protobuf ==

load("@build_stack_rules_proto//deps:prebuilt_protoc_deps.bzl", "prebuilt_protoc_deps")

prebuilt_protoc_deps()

load("@build_stack_rules_proto//deps:protobuf_core_deps.bzl", "protobuf_core_deps")

protobuf_core_deps()

# == gRPC Gateway ==

load("@build_stack_rules_proto//deps:grpc_gateway_deps.bzl", "grpc_gateway_deps")

grpc_gateway_deps()

load("@build_stack_rules_proto//deps:grpc_gateway_openapiv2_deps.bzl", "grpc_gateway_openapiv2_deps")

grpc_gateway_openapiv2_deps()

# == protoc-gen-validate == #

load("@build_stack_rules_proto//deps:protoc_gen_validate_deps.bzl", "protoc_gen_validate_deps")

protoc_gen_validate_deps()

load("@build_stack_rules_proto//rules/proto:proto_repository.bzl", "proto_repository")

proto_repository(
    name = "protoc_gen_validate",
    build_directives = [
        "gazelle:proto_language go enabled true",
    ],
    build_file_generation = "on",
    build_file_proto_mode = "file",
    cfgs = ["//:config.yaml"],
    override_go_googleapis = True,
    # sha256 = "b9dbc65ebc738a486265ef7b708e9449bf361541890091983e946557ee0a4bfc",
    type = "zip",
    urls = ["https://github.com/envoyproxy/protoc-gen-validate/archive/refs/tags/v0.6.7.zip"],
)
